---
title: "PLN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
```


```{r}
file <- read.csv("pln.csv", header=TRUE)
file <- file[,c(1,2,3,6)]
file
colnames(file)<-c("Sample1","Sample2","TRIBES_cM","TRIBES_EstDegree")
file$TRIBES_EstDegree[file$TRIBES_EstDegree=="PO"] <- 1
#file <- transform(file, "Estdegree" = as.numeric("Estdegree"))
file <- transform(file, TRIBES_EstDegree = as.numeric(TRIBES_EstDegree))  # Make Est_degree a numeric colomn.
file
table <- datatable(file, rownames = FALSE) %>%formatStyle(columns="TRIBES_EstDegree",
              background= styleEqual(c(0,1,2,3,4,5,6,7,8,9), c("green","green","green","green","green","green","green","green","yellow","orange"))
              )
table
```
```{r}
samples <- c()
for(i in file$Sample1){ # iterate over column Sample1
	if(! i %in% samples){ # if i is not in samples, append i to vector samples.
    		samples <- c(samples, i)}
}
samples
```
#### Vector "samples_2"
Create vector "samples_2", containing the unique sample names from 
column "Sample2" dataframe file.
```{r}
samples_2 <- c()
for(i in file$Sample2){ # iterate over column Sample2
        if(! i %in% samples_2){ # if i is not in samples_2, append i to vector samples_2.
                samples_2 <- c(samples_2, i)}
}
samples_2
```
#### Vector "unique"
Create vector "unique".
Compare "samples" and "samples_2". Store only unique values in vector "unique".
```{r}
unique <- c() # create empty vector
for(i in samples){  # iterate over vector "samples"
  # if item from "samples" vector not in vector "samples_2", append to vector "unique"
	if(!i %in% samples_2){  
		unique <- c(unique, i)}
}
unique
for(i in samples_2){  # iterate over vector "samples_2"
unique <- c(unique, i)} # append all items from vector "samples_2"
unique
```
#### Check vector "unique"
```{r}
entries <- length(unique)
entries   # check if the amount of values in vector "unique" is correct.
```
### Create matrix
Determine size of matrix: N x N size.
```{r}
size_matrix <- (entries * entries)  # determine size of matrix 
size_matrix
```
Create matrix.
```{r}
# create matrix
matrix <- matrix(1:size_matrix, nrow=entries, ncol=entries)
rownames(matrix) <- unique  # add rownames to matrix
colnames(matrix) <- unique  # add column names to matrix
matrix
```
```{r}
# create matrix
matrix_2 <- matrix(1:size_matrix, nrow=entries, ncol=entries)
rownames(matrix_2) <- unique  # add rownames to matrix
colnames(matrix_2) <- unique  # add column names to matrix
matrix_2
```


Change values in matrix.
```{r}
for(i in matrix){   # for value in matrix
k <- arrayInd(i, dim(matrix))   # get position of rowname and column name, store value in k
# get row name and columnname based on location 'k', store value in "names"
names <- mapply(`[[`, dimnames(matrix), k)
# create subset where the sample names in names are the same as in dataframe file, where the sample names are in the same row. 
# if no match is found, data is empty.
data <- subset(file, (Sample1==names[1] & Sample2 ==names[2]) | (Sample2==names[1] & Sample1 == names[2]))
if(length(data$Sample1)==0){  # if data is empty
          matrix[k[1],k[2]] <- 1  # 
        }else{  # if data is not empty
          matrix[k[1],k[2]] <- data$TRIBES_cM  # value in matrix = cM
        }
if(names[1]==names[2]){   # if the sample names are the same
          matrix[k[1], k[2]] <- 0}  # value = 0
}
```
```{r}
print(matrix)
```


```{r}
# For the estimate degree
for(i in matrix_2){   # for value in matrix
k <- arrayInd(i, dim(matrix_2))   # get position of rowname and column name, store value in k
# get row name and columnname based on location 'k', store value in "names"
names <- mapply(`[[`, dimnames(matrix_2), k)
# create subset where the sample names in names are the same as in dataframe file, where the sample names are in the same row. 
# if no match is found, data is empty.
data <- subset(file, (Sample1==names[1] & Sample2 ==names[2]) | (Sample2==names[1] & Sample1 == names[2]))
#print(data)
if(length(data$Sample1)==0){  # if data is empty
          matrix_2[k[1],k[2]] <- 12  # 
        }else{  # if data is not empty
          matrix_2[k[1],k[2]] <- data$TRIBES_EstDegree  # value in matrix = cM
        }
if(names[1]==names[2]){   # if the sample names are the same
          matrix_2[k[1], k[2]] <- 0}  # value = 0
}
#print(matrix_2)
```

```{r}
print(matrix)
```

```{r}
print(dist(matrix, method="manhattan"))

```

```{r}
par(cex=0.5,font=3)
library(ape)
plot(as.phylo(avg_cM), type = "fan")
avg_cM <- (hclust(dist(matrix, method="manhattan"), method="single"))
dendo <- as.dendrogram(avg_cM) 
par(cex=0.7,font=3)
#dendo <- dendo %>% set("leaves_pch", 1) %>% set("leaves_cex", 2) %>% set("leaves_col", ifelse(labels(dendo) %in% unique_8, "red", "black"))
plot(dendo, ylab="Distance")
title("Cluster dendogram based on cM TRIBES")
mtext(text = "Sample", side = 1, line = 1, col = "black", adj = -.005)
```

```{r}
par(cex=0.5,font=3)
library(ape)
plot(as.phylo(avg_cM), type = "fan")
avg_cM <- (hclust(dist(matrix_2, method="manhattan"), method="single"))
dendo <- as.dendrogram(avg_cM) 
par(cex=0.7,font=3)
dendo <- dendo %>% set("leaves_pch", 1) %>% set("leaves_cex", 2) %>% set("leaves_col", ifelse(labels(dendo) %in% unique_8, "red", "black"))
plot(color_labels(dendo, col = ifelse(labels(dendo) %in% unique_8, "red", "black")), ylab="Distance")
title("Cluster dendogram based on Estimate degree TRIBES")
mtext(text = "Sample", side = 1, line = 1, col = "black", adj = -.005)
```
