---
title: "IBD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r}
#args<-commandArgs(TRUE)    # Use when script is finished
file <- read.table("pln.match", sep="\t")
file <- file[,c(1,3,5,6,7)]
colnames(file) <- c("Sample1","Sample2","Chromosome", "Start", "End")
samples <- unique(file[c("Sample1")])
samples <- as.vector(t(samples))
samples_2 <- unique(file[c("Sample2")])
samples_2 <- as.vector(t(samples_2))
merged <- c(samples, samples_2)
merged

```

```{r}
start = 118869461
end = 118881893
entries <- data.frame(Sample1=character(), Sample2=character(), Chromosome=character(),
                      Start=character(), End=character())   # make dataframe with empty columns
for(entry in 1:nrow(file)){   # iterate over rows in dataframe "file"
  # add entry to dataframe "entries" when start is same or lower and end is same or higher
  if(file[entry,"Start"] <= start & file[entry,"End"] >= end){  
    entries <- rbind(entries, file[entry,])
  }
}
entries
str(entries)  # print structure of entries
chr6 <- subset(entries, Chromosome == 6, select= Sample1:End)   # Store only entries where chromosome is 6
chr6

```
library(ggplot2)
text = paste("")
ggplot(aes()) 

```{r}
samples <- unique(chr6[c("Sample1")])
samples <- as.vector(t(samples))
samples
samples_2 <- unique(chr6[c("Sample2")])
samples_2
samples_2 <- as.vector(t(samples_2))
merge <- c(samples, samples_2)
merge   # check how many samples have the pln region
```



```{r}
library(ggplot2)
plot <- ggplot(chr6, aes(Start), col=c(rainbow(length(chr6$Start)))) + xlim(c(min(entries[,4]), max(entries[,5])))
y = 0
for(row in 1:nrow(chr6)){
  # add lines per IBD segment
  # size = 0.1, so there is space between the lines
  plot <- plot + geom_segment(x= chr6[row,4], xend = chr6[row,5], y = y , yend = y, size=0.1)
  y <- y + 0.05   # add to y, so the lines are shown above each other
}
print(y)
print(length(chr6$Start))
plot <- plot + expand_limits(y = c(1, 34))  # set the y as 
plot

```

